name: Build and Publish .exe

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build and Publish .exe
      run: dotnet publish -c Release -o publish PersonNummerValidationTool/PersonNummerValidationTool.csproj

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: Published
        path: publish/PersonNummerValidationTool/**/*.exe
