name: Build and Publish

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build and Publish
      run: |
        dotnet restore --runtime win-x64
        dotnet publish -c Release -o publish/PersonNummerValidationTool --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:UseAppHost=true --runtime win-x64
      working-directory: PersonNummerValidationTool

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: Published
        path: PersonNummerValidationTool/publish/*.exe
