name: Build C# Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' 

    - name: Build
      run: dotnet build -c Release

    - name: Publish EXE
      run: dotnet publish -c Release 

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: Published .exe
        path: bin/Release/netcoreapp3.1/win10-x64/publish/
