name: .NET Core CI

on:
  push:
    branches:
      - main  # eller annat
      - Andreybranch
      - Niklasbranch
      - master
      pull_request:
      branches:
      - main
      - Andreybranch
      - Niklasbranch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 'latest'  # eller den version du vill använda

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal